In [1]:
import numpy as np

In [2]:
np.array([1,2,3], dtype='complex')

array([1.+0.j, 2.+0.j, 3.+0.j])

### Data-type consisting of more than one element:

In [3]:
np.array([[1,2,3],[4,5,6]], dtype=[('a', '<i2'), ('b', '<i4')])

array([[(1, 1), (2, 2), (3, 3)],
       [(4, 4), (5, 5), (6, 6)]], dtype=[('a', '<i2'), ('b', '<i4')])

In [5]:
np.array([[1,2,3],[4,5,6]], dtype=[('a', '<i2'), ('b', 'complex'), ('c', '<i4')])

array([[(1, 1.+0.j, 1), (2, 2.+0.j, 2), (3, 3.+0.j, 3)],
       [(4, 4.+0.j, 4), (5, 5.+0.j, 5), (6, 6.+0.j, 6)]],
      dtype=[('a', '<i2'), ('b', '<c16'), ('c', '<i4')])

In [7]:
np.array([(1,2),(4,5)], dtype=[('a', '<i2'), ('b', 'complex')])

array([(1, 2.+0.j), (4, 5.+0.j)], dtype=[('a', '<i2'), ('b', '<c16')])

In [8]:
np.array([(1,2),(4,5), (3,6), (7,8)], dtype=[('a', '<i2'), ('b', 'complex')])

array([(1, 2.+0.j), (4, 5.+0.j), (3, 6.+0.j), (7, 8.+0.j)],
      dtype=[('a', '<i2'), ('b', '<c16')])

In [9]:
issubclass(np.mat, np.array)

TypeError: issubclass() arg 1 must be a class

In [10]:
type(np.mat)

function

In [11]:
type(np)

module

In [12]:
type(np.bitwise_xor)

numpy.ufunc

In [14]:
print(dir(np)[:20])

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf']


In [15]:
a=10
b=11
a is b

False

In [16]:
a=10
b=10
a is b

True

In [17]:
a=1000
b=1000
a is b

False

In [20]:
#Creating array from subclasses
np.mat(np.array([[1,2], [4,5]]))

matrix([[1, 2],
        [4, 5]])

In [24]:
np.mat('1 2 ; 3 4')

matrix([[1, 2],
        [3, 4]])

In [25]:
np.mat('1 2 3; 4 5 6; 4 5 7;7 8 9; 2 4 6')

matrix([[1, 2, 3],
        [4, 5, 6],
        [4, 5, 7],
        [7, 8, 9],
        [2, 4, 6]])

## numpy.asarray

In [27]:
lst = [1,2,3,4]
type(np.array(lst))

numpy.ndarray

In [28]:
np.asarray((1,2,3))

array([1, 2, 3])

In [29]:
np.array([1,2])

array([1, 2])

In [30]:
type(np.asarray((1,2,3)))

numpy.ndarray

In [34]:
a = np.array([1,2,3, 4.0], dtype=np.float32)
a

array([1., 2., 3., 4.], dtype=float32)

In [38]:
a = np.array([1,2,3, 4.0], dtype='float')
a

array([1., 2., 3., 4.])

In [39]:
a = np.array([1,2,3], dtype=np.float32)
a


array([1., 2., 3.], dtype=float32)

In [40]:
np.asarray(a) is a

True

In [41]:
np.asarray(a, dtype=np.float64) is a

False

In [43]:
a = np.array([5,6])

In [44]:
np.asarray(a) is a

True

In [45]:
np.asarray(a, dtype=np.float) is a

False

In [46]:
type(np.asanyarray([1,2,3]))

numpy.ndarray

In [47]:
a= np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [48]:
np.asanyarray(a) is a

True

In [50]:
np.asanyarray([1,2])

array([1, 2])

In [53]:
np.asanyarray((1,2))

array([1, 2])

In [58]:
np.asanyarray({1,2})

array({1, 2}, dtype=object)

In [61]:
a = np.matrix([1,2])
a

matrix([[1, 2]])

In [63]:
a =np.array([1,2,3], copy=True)

In [64]:
b = a

In [65]:
b[0] = 5

In [66]:
a

array([5, 2, 3])

In [67]:
b

array([5, 2, 3])

In [68]:
#Create an array x, with a reference y and a copy z:

In [69]:
x = np.array([1,2,3])
y=x

In [72]:
print(x)
print(y)

[1 2 3]
[1 2 3]


In [74]:
z = x.copy()

In [75]:
print(z)

[1 2 3]


In [76]:
x[0]= 34

In [77]:
print(x)
print(y)
print(z)

[34  2  3]
[34  2  3]
[1 2 3]


## numpy.fromfunction

In [78]:
arr = np.fromfunction(lambda x,y : x==y, (4,4))

In [79]:
arr

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [82]:
arr = np.fromfunction(lambda x, y : x*y, (4,4))

In [83]:
arr

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [85]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [150]:
#Create a new 1-dimensional array from an iterable object.
np.array([1,2,3])

array([1, 2, 3])

In [151]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001E687B237B0>

In [154]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [158]:
#A new 1-D array initialized from text data in a string
text_data = "1 2 3 4"
np.fromstring(text_data, sep=' ')

array([1., 2., 3., 4.])

In [159]:
np.fromstring('1,2,3', sep=',')

array([1., 2., 3.])

In [160]:
np.fromstring('1,2,3', dtype=int, sep=',')

array([1, 2, 3])

In [161]:
# How to create create a record array from a (flat) list of arrays
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])

In [164]:
record = np.core.records.fromarrays([x1,x2,x3,x4], names=['a','bb', 'cc', 'dd'])

In [165]:
record

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('bb', '<U3'), ('cc', '<f8'), ('dd', '<f8')])

In [168]:
record[1]

(2, 'dd', 2., 2.)

In [170]:
record[3]

(4, '12', 4., 4.)

In [171]:
record[1]['cc']

2.0

In [172]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)

In [174]:
type(mat)

numpy.ndarray

In [175]:
mat.dtype

dtype('float64')

In [176]:
mat

array([[1.1, 2. , 3. ],
       [4. , 5.2, 6. ],
       [7. , 8.3, 9. ]])

In [177]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [178]:
np.arange(5,16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [179]:
np.arange(5,16,2.5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

In [182]:
np.arange(50, 0, -5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [183]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [188]:
np.ones((3,4)) +5


array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [189]:
5+ np.ones((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [192]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [191]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [198]:
np.logspace(2,4,8, base=10, endpoint=False)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        , 1778.27941004, 3162.27766017, 5623.4132519 ])

In [204]:
x =np.arange(16).reshape(-1,4)

In [202]:
np.arange(16).reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [203]:
np.arange(16).reshape(-1,9)

ValueError: cannot reshape array of size 16 into shape (9)

In [208]:
print(x)
np.diag(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 0,  5, 10, 15])

In [210]:
np.diag(x, k=1)

array([ 1,  6, 11])

In [211]:
np.diag(x, k=3)

array([3])

In [212]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [213]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [214]:
np.diag(np.diag(np.diag(x)))

array([ 0,  5, 10, 15])

In [215]:
np.diag(np.diag(np.diag(np.diag(x))))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [216]:
#Create a two-dimensional array with the flattened input as a diagonal.

np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [217]:
np.diagflat([1,2], k=1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [218]:
np.diagflat([1,2], k=5)

array([[0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [219]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [220]:
np.tri(4, k=2)

array([[1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [221]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [224]:
start =np.zeros((4,4))
start

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [225]:
start + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [226]:
start1 = start +1


In [227]:
start1 *4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [230]:
add1 = np.array([2,3,4,5])


In [232]:
start1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [231]:
start1 + add1

array([[3., 4., 5., 6.],
       [3., 4., 5., 6.],
       [3., 4., 5., 6.],
       [3., 4., 5., 6.]])

In [233]:
start1 * add1

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [234]:
add_cols = np.array([[5,6,7,8]])

In [235]:
add_cols

array([[5, 6, 7, 8]])

In [239]:
add_cols = add_cols.T
add_cols

array([[5],
       [6],
       [7],
       [8]])

In [241]:
start1 * add_cols

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.]])

In [242]:
for i in range(3):
    start1 = start1 * add_cols

In [243]:
start1

array([[125., 125., 125., 125.],
       [216., 216., 216., 216.],
       [343., 343., 343., 343.],
       [512., 512., 512., 512.]])