In [62]:
import numpy as np

In [1]:
import pandas as pd

In [2]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')   
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [4]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [5]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
titanic_train['PassengerId'].dtype

dtype('int64')

In [16]:
titanic_train.dtypes[titanic_train.dtypes == 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [14]:
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index

In [15]:
a

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [19]:
titanic_train.dtypes[titanic_train.dtypes == 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [21]:
titanic_train[a].describe()

Name   Sex Ticket        Cabin Embarked
count             156   156    156           31      155
unique            156     2    145           28        3
top     Bing, Mr. Lee  male  11668  C23 C25 C27        S
freq                1   100      2            2      110

In [22]:
titanic_train[a]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female   
152                                   Meo, Mr. Alfonzo    male   
153                    van Billiard, Mr. Austin Blyler    male   
154                              Olsen, Mr. Ole Martin    male   
155                        Williams, Mr. Charles Duane    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
151            113776    C2        S  
152        A.5. 11206   NaN        S  
153          A/5. 851   NaN        S  
154         Fa 265302   NaN        S  
155          PC 17597   NaN        C  

[156 rows x 5 columns]

In [23]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [25]:
titanic_train.dtypes[titanic_train.dtypes=='object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [26]:
sorted(titanic_train)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'Ticket']

In [31]:
sorted(titanic_train['Name'])[4:12:3]

['Andersson, Mr. Anders Johan',
 'Andrew, Mr. Edgardo Samuel',
 'Attalah, Miss. Malake']

In [33]:
titanic_train['Name'].describe()

count               156
unique              156
top       Bing, Mr. Lee
freq                  1
Name: Name, dtype: object

In [34]:
titanic_train['Ticket'][4:8]

4    373450
5    330877
6     17463
7    349909
Name: Ticket, dtype: object

In [35]:
titanic_train['Ticket'].describe()

count       156
unique      145
top       11668
freq          2
Name: Ticket, dtype: object

In [37]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [38]:
titanic_train['newcol'] = "data333"

In [39]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   newcol  
0      0         A/5 21171   7.2500   NaN        S  data333  
1      0          PC 17599  71.2833   C85        C  data333  
2      0  STON/O2. 3101282   7.9250   NaN        S  data333  
3      0            113803  53.1000  C123        S  data333  
4      0            373450   8.0500   NaN        S  data333

In [41]:
titanic_train['Cabin'][4:7]

4    NaN
5    NaN
6    E46
Name: Cabin, dtype: object

In [42]:
titanic_train['Cabin'].nunique()

28

In [43]:
titanic_train['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [44]:
pd.Categorical(['a', 'b', 'c', 'a', 'b', 'c'])

[a, b, c, a, b, c]
Categories (3, object): [a, b, c]

In [45]:
pd.Categorical(titanic_train['Pclass'])

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [47]:
categories = pd.Categorical(titanic_train['Cabin'])

In [49]:
type(categories)

pandas.core.arrays.categorical.Categorical

In [50]:
categories

[NaN, C85, NaN, C123, NaN, ..., C2, NaN, NaN, NaN, NaN]
Length: 156
Categories (28, object): [A5, A6, B28, B30, ..., F G73, F2, F33, G6]

In [52]:
titanic_train['Cabin'].astype(str)

0       nan
1       C85
2       nan
3      C123
4       nan
       ... 
151      C2
152     nan
153     nan
154     nan
155     nan
Name: Cabin, Length: 156, dtype: object

In [54]:
str_cabin = titanic_train['Cabin'].astype(str)

In [58]:
char_cabin = [cabin[0]   for cabin in str_cabin]

In [60]:
titanic_train['Cabin1'] = char_cabin

In [61]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   newcol Cabin1  
0      0         A/5 21171   7.2500   NaN        S  data333      n  
1      0          PC 17599  71.2833   C85        C  data333      C  
2      0  STON/O2. 3101282   7.9250   NaN        S  data333      n  
3      0            113803  53.1000  C123        S  data333      C  
4      0            373450   8.0500   NaN        S  data333      n

In [64]:
np.where(titanic_train['Age'].isnull())

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [65]:
missing = np.where(titanic_train['Age'].isnull() == True)

In [66]:
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [67]:
np.where(titanic_train['Fare'] == max(titanic_train['Fare']))

(array([27, 88], dtype=int64),)

In [69]:
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [72]:
len(missing[0])

30

In [73]:
type(missing)

tuple

In [76]:
type(missing[0])

numpy.ndarray

In [80]:
titanic_train['Family'] = titanic_train['SibSp'] + titanic_train['Parch']
titanic_train['Family']

0      1
1      1
2      0
3      1
4      0
      ..
151    1
152    0
153    2
154    0
155    1
Name: Family, Length: 156, dtype: int64